### ISSUE TITLE
BRON\example_data\example_input_data\starting_point_tactic.csv Why does the file have no data?

### ISSUE THREAD

**Issue by wsj970619** [ALFA-group/BRON#24]
![image](https://user-images.githubusercontent.com/32978521/111952724-83b7b080-8b20-11eb-9001-36aa5a53eed1.png)
![image](https://user-images.githubusercontent.com/32978521/111952800-a1851580-8b20-11eb-90e2-af64fabb6fdf.png)
This is the result of my notes.

**Comment by hembergerik** [comment]
I believe this is fixed by #26
