### ISSUE TITLE
ModuleNotFoundError: No module named 'meta_analysis'

### ISSUE THREAD

**Issue by alexrebell** [ALFA-group/BRON#30]
Hi!
I installed everything as specified in the instructions.
When starting the file **bron_arango.py** returns the error: **Module Not Found Error: No module named 'meta_analysis'.**

What to do?

**Comment by hembergerik** [comment]
It could be that your `PYTHONPATH` is not set correctly. I usually run it like below from the root of the repository:
```
PYTHONPATH graph_db/bron_arango.py
```

**Comment by alexrebell** [comment]
@hembergerik thank you very much!
