### ISSUE TITLE
Is BRON contains mobile tactics on MITRE ATT&CK ?

### ISSUE THREAD

**Issue by HarrialX** [ALFA-group/BRON#32]
Hi Dear Author,

Thanks for contributing this brilliant work! After constructing a BRON graph followed by your instructions, I found that the tactics only contain the "enterprise tactics", which is shown in [https://attack.mitre.org/tactics/enterprise/](https://attack.mitre.org/tactics/enterprise/)

At the same time, MITRE ATT&CK also contains a group of "mobile tactics", as shown in [https://attack.mitre.org/tactics/mobile/](https://attack.mitre.org/tactics/mobile/) . Does BRON also contain this part of tactics linking to techniques (then attack patterns -> CWEs -> etc) ? 

Additionally, could I ask about how do you link the techniques (from MITRE ATT&CK) with attack patterns (from CAPEC)? It seems challenging to find data sources that directly link those two parts.

Thanks!

**Comment by hembergerik** [comment]
Thank you for your questions.
- BRON currently only includes the "enterprise tactics". However it should be possible to support the "mobile tactics" and then link to CAPEC etc. if there are links listed in the data sources
- The technique-attack pattern link is indicated in the existing technique and attack pattern data sources. Yes it is challenging to infer links in BRON, for some attempts see https://arxiv.org/abs/2108.02618

**Comment by HarrialX** [comment]
Cool, thanks for your responses.
