### ISSUE TITLE
TechniqueCapec.json is empty

### ISSUE THREAD

**Issue by jiangdie666** [ALFA-group/BRON#38]
After the container bronbootstrap finished downloading the data, there should be something wrong when associating the capec and technique data, resulting in no data transfer with the database.
![image](https://github.com/ALFA-group/BRON/assets/72592733/6fff81f6-759e-4523-bed3-0c9a3cc62cfd)
When checking the front end of the database, I found that all other data were intact, only TechniqueCapec was empty.
![image](https://github.com/ALFA-group/BRON/assets/72592733/9fc50851-44f4-4661-a323-60bbeab2df41)
At first I thought there was a problem with the transfer, so I opened the container to check the TechiniqueCapec.json and found that it was empty, but the capec.json and Techinique.json were normal.
![image](https://github.com/ALFA-group/BRON/assets/72592733/56d554ef-1956-4a98-a491-10626c0c44c7)
Please allow me to ask if there is some problem with the code that causes the association to fail.
[](download_threat_information/parsing_scripts/parse_attack_tactic_technique.py)

**Comment by hembergerik** [comment]
Thanks. I will look into it. It could be that the input data for techniques and/or CAPEC has changed.

**Comment by jiangdie666** [comment]
There is a small problem, I read the code did not find how the cpe data is saved, he is from the cve configurations field cpe23Uri extracted one by one?

**Comment by hembergerik** [comment]
Hopefully #39 fixes the issue of Technique and CAPEC links. 

Yes, the cpe uris are extracted one by one. I do not believe this should affect the issue. I think it had to do with a change in the ATT&CK data.
